# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f851674bf42502a5fd5509eedfb7fcea083f8380811b946457127ccd67a130ddfce6daf469ec8e443bd61748dc84aa8f31d953f61ad79ebbecb646c1babc47

test:
  secret_key_base: faad96016e2613b2eb1432d48d70e094ad60a25357da26a40f750fb4a863c0a0cf7832bda71f0850d1885d831b29b175ee4417b81d2b6c94fee10ef07a9f10ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
